server {
    listen 80;
    server_name _;

    root /usr/share/nginx/html;
    index index.html;

    # O fallback mágico para Single Page Applications (SPA) como o React
    location / {
        try_files $uri $uri/ /index.html;
    }
}
